### ISSUE TITLE
Data Catalogue - Tools and Methods - Add Content

### ISSUE THREAD

**Issue by andy-clarke-uofg** [urbanbigdatacentre/ubdc.ac.uk#13]
Write description for Data Catalogue and add links + description for the tools and methods sections

What are tools and methods??

**Comment by andy-clarke-uofg** [comment]
Unlock the potential of a wide range of key datasets to empower and inform your research with free access to our comprehensive data catalogue

**Comment by ghost** [comment]
Need copy of Tools and Methods
