### ISSUE TITLE
Cookies Banner

### ISSUE THREAD

**Issue by andy-clarke-uofg** [urbanbigdatacentre/ubdc.ac.uk#2]
Banner does match design 

![Image](https://github.com/urbanbigdatacentre/ubdc.ac.uk/assets/56840824/84c5f3fd-871a-4f86-af36-5449928d4d72)

**Comment by andy-clarke-uofg** [comment]
This issue is with VEZA

**Comment by ghost** [comment]
Correct design: 

![image](https://github.com/urbanbigdatacentre/ubdc.ac.uk/assets/138020979/3289c0b8-2910-44a9-95fb-cb8bc3e7a762)

**Comment by andy-clarke-uofg** [comment]
VEZA: Are we able to allow users to naviagte the page without accepting or declining the cookies banner

**Comment by andy-clarke-uofg** [comment]
Conversation with VEZA: 

- They will update cookies banner design to match the figma
- User should be able to interact with call to actions without having to interact with cookies banner

**Comment by Basolanilla** [comment]
@andymithamclarke @ErmiaUOG Please see below cookie requirements. 

Cookie modifications required for GDPR compliance: 

1. add a "reject cookies button" in the banner next to the "accept cookies"

Behaviour for compliance: compliance is achieved by a positive, clear, no-directed action. Meaning the user has to freely and clearly give consent. This means: 
•	Only clicking on "accept cookies" or toggling-on a cookie category, these cookies can be launched. 
•	Any other action means "NO, I don't consent": 
o	Clicking on reject cookies
o	Clicking on the X button on the preference centre
o	Not interacting with the banner
•	The banner must be present on the screen until the user interacts with it. If the user does not interact with the banner, the banner will continue to be present on navigation BUT
•	The banner cannot be a “wall” for users. Meaning the user should be able to navigate on the site (scroll up and down, move through pages, click on the elements of the site)
