### ISSUE TITLE
Impact Story Child Page - Sidebar Nav Position not Fixed

### ISSUE THREAD

**Issue by andy-clarke-uofg** [urbanbigdatacentre/ubdc.ac.uk#25]
Content is being hidden because the user cannot scroll down the navbar

![Image](https://github.com/urbanbigdatacentre/ubdc.ac.uk/assets/56840824/7eb0e87d-ec5b-4b20-aad6-57dd77108c14)

**Comment by ghost** [comment]
Can not reproduce it @andymithamclarke
