### ISSUE TITLE
Events child pages - update to dynamic picture

### ISSUE THREAD

**Issue by Basolanilla** [urbanbigdatacentre/ubdc.ac.uk#66]
@ErmiaUOG 

Suzanne reported that the child pages for events have the same heading image (the static image of people clapping) than on the events homepage. Ideally, we want the image for each event to be unique, and to match the image that appears on the preview. 

Can you please look into it and let me know what can be done? 

Thanks, 
B

![Image](https://github.com/urbanbigdatacentre/ubdc.ac.uk/assets/136359697/44b49d8f-e1d4-4f80-b7ff-21c818f5aba2)
![Image](https://github.com/urbanbigdatacentre/ubdc.ac.uk/assets/136359697/8191ca9b-7bdb-492f-80bb-0c4ea10559be)

**Comment by ghost** [comment]
@Basolanilla fixed.
