### ISSUE TITLE
Addition of publications module underneath each author page

### ISSUE THREAD

**Issue by Basolanilla** [urbanbigdatacentre/ubdc.ac.uk#70]
Now that the publications section is completed and we have content, we need to bring this content to underneath each author's page. The original website design involved feeding content through different sections of the site to make it easier for users to find content and bringing related and relevant content to the surface. 
Within each authors page, at the bottom, there should be a secondary module (carrousel style) linking to publications from said author. When an author doesn't have any publications, this module should be hidden.

**Comment by ghost** [comment]
@Basolanilla please check this link: https://www.ubdc.ac.uk/author/nick-bailey

**Comment by Basolanilla** [comment]
@ErmiaUOG Please see below comments: 

1. the publications display as a list of hyperlinks below the author's bio. This should be a carrousel instead, similar to the related content. With thumbnails instead of images or with just title and description. Similar to this: https://www.ubdc.ac.uk/data-theme/transport-and-mobility
2. in some cases the first item of the list does not appear as a hyperlink at all. See https://www.ubdc.ac.uk/author/joao-porto-de-albuquerque 
3. the title "publications" is a different size than the previous heathers (positions). This needs to align. 
4. In several pages, there is an error message displaying "no items found". If no publications are available for the user, this module should be hidden. Not displaying an error message. https://www.ubdc.ac.uk/author/simon-joss

**Comment by Basolanilla** [comment]
Hi @ErmiaUOG,

I checked the Publications module underneath the author's page (see example here: https://www.ubdc.ac.uk/author/nick-bailey). Please see feedback below: 

- the scorecards have different heights. Needs to be fixed. 
- Can we add a thumbnail like the one attached? 
- change CTA from "learn more" to "view publication" 
- the card brings the title and date. Can we add a one line description as well? 
- not sure about the date on the scorecard as some are quite old (see example above publications are from 1994).

![Image](https://github.com/user-attachments/assets/fa391036-b950-43b4-9d95-1b4bb1638ef7)

**Comment by ghost** [comment]
>the card brings the title and date. Can we add a one line description as well? 

we do not have abstracts
