### ISSUE TITLE
Incorrect CTA design on homepage - review

### ISSUE THREAD

**Issue by Basolanilla** [urbanbigdatacentre/ubdc.ac.uk#71]
I noticed that the CTAs of some modules on the homepage have a different look and feel. The background colour is a bright orange and they look slightly off compared to the other CTAS of the site. This is new, and it seems to be affecting orange CTAs only. See screenshots below:  
![Image](https://github.com/user-attachments/assets/832f876d-83bb-4337-b226-aa5ec96d154b)

 
![Image](https://github.com/user-attachments/assets/10a5ba36-56c0-493a-bc9e-7d07c814633f)

**Comment by ghost** [comment]
@Basolanilla fixed 🙏 



![Image](https://github.com/user-attachments/assets/04411ae5-f656-41c3-9e5a-760d361b5bb0)
